package utils

const SuccessCreatedUser = "Successfully created user"
const FailCreatedUser = "Failed created user"
const SuccessUpdatedUser = "Successfully updated user"
const FailUpdatedUser = "Failed updating user"
const SuccessRetrievedUser = "Successfully retrieved user"
const FailRetrievedUser = "Failed retrieving user"
const SuccessDeletedUser = "Successfully deleted user"
const FailDeletedUser = "Failed deleting user"

const SuccessCreatedPoll = "Successfully created poll"
const FailCreatedPoll = "Failed created poll"
const SuccessUpdatedPoll = "Successfully updated poll"
const FailUpdatedPoll = "Failed updating poll"
const SuccessRetrievedPoll = "Successfully retrieved poll"
const FailRetrievedPoll = "Failed retrieving poll"
const SuccessDeletedPoll = "Successfully deleted poll"
const FailDeletedPoll = "Failed deleting poll"

const SuccessSignedUp = "Successfully signed up"
const FailSignedUp = "Failed signed up"
const SuccessLoggedOut = "Successfully logged out"
const FailloggedOut = "Failed logged out"
const SuccessRefreshed = "Successfully refreshed"
const FailRefreshed = "Failed refreshed"
const SuccessLogin = "Successfully login"
const FailLogin = "Failed login"

const SuccessCreatedSessionToken = "Successfully created session token"
const FailCreatedSessionToken = "Failed created session token"
const SuccessUpdatedSessionToken = "Successfully updated session token"
const FailUpdatedSessionToken = "Failed updated session token"
